{% set name = "emela" %}
{% set version = "1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gstagnit/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 53a867616f7ae0b03928c5a9db4b1b04a6b29794c9492a96b19dfea64b1c856d
  folder: source
  patches:
    - 0001-support-range-of-cmakes.patch

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('emela', max_pin='x.x') }}
  script:
    - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DWITH_LHAPDF=ON -S source -B build
    - cmake -LH build
    - cmake --build build --clean-first --parallel="${CPU_COUNT}"
    - cmake --install build

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - libboost-devel
    - lhapdf
  run:
    - lhapdf

test:
  source_files:
    - source/example
  requires:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - curl
    - tar
  commands:
    - test -f $PREFIX/include/eMELA/version.h
    - test -f $PREFIX/include/eMELA/bspdf.hh
    - test -f $PREFIX/include/eMELA/analytics.hh
    - test -f $PREFIX/include/eMELA/specialfunctions.hh
    - test -f $PREFIX/include/eMELA/version.h.in
    - test -f $PREFIX/include/eMELA/constants.hh
    - test -f $PREFIX/include/eMELA/eMELA.hh
    - test -f $PREFIX/include/eMELA/grid.hh
    - test -f $PREFIX/include/eMELA/ilc500.hh
    - test -f $PREFIX/include/eMELA/numerics.hh
    - test -f $PREFIX/lib/libeMELA${SHLIB_EXT}
    - test -f $PREFIX/bin/eMELA-config

    - eMELA-config --help
    - eMELA-config --prefix
    - eMELA-config --incdir
    - eMELA-config --libdir
    - eMELA-config --data
    - eMELA-config --cppflags
    - eMELA-config --cxxflags
    - eMELA-config --ldflags

    - cd source/example
    - $CXX CreateGrid.cc -o CreateGrid $CXXFLAGS $LDFLAGS $(eMELA-config --ldflags)
    # Skip as extremely slow with 50000 grid points
    # - ./CreateGrid NLL DELTA MSBAR
    - test -f ./CreateGrid
    - $CXX GetPdf.cc -o GetPdf $CXXFLAGS $LDFLAGS $(eMELA-config --ldflags)
    - ./GetPdf

    # Download the grids from the GitHub releases page
    # https://github.com/gstagnit/eMELA/releases/tag/v1.0
    - curl -sLO https://github.com/gstagnit/eMELA/releases/download/v1.0/grids.tar.gz
    - tar -xzf grids.tar.gz
    - export LHAPDF_DATA_PATH=$(readlink -f ./grids):$(lhapdf-config --datadir):$LHAPDF_DATA_PATH

    - $CXX GetPdfGrid.cc -o GetPdfGrid $CXXFLAGS $LDFLAGS $(eMELA-config --ldflags) $(lhapdf-config --ldflags)
    - ./GetPdfGrid

about:
  home: https://github.com/gstagnit/eMELA
  summary: 'emela: an improved QED-version of MELA'
  description: |
    ``eMELA`` is a library that implements the evolution in pure QED of the
    unpolarised electron parton distribution functions (PDFs) up to
    next-to-leading logarithmic (NLL) approximation, according to the papers
    listed on the GitHub repository. ``eMELA`` includes the evolution with
    multiple fermion families and their mass thresholds, and it gives one the
    possibility of choosing among three different UV-renormalisation schemes
    (`MSBAR`: $\overline{\rm MS}$, `ALPMZ`: $\alpha(m_Z)$, `ALGMU`: $G_\mu$)
    and two different factorisation schemes
    (`MSBAR`: $\overline{\rm MS}$, `DELTA`: $\Delta$).

    More in detail, ``eMELA`` is an improved QED-version of
    [MELA](https://github.com/vbertone/MELA). It consists of a Fortran code
    responsible for the numerical evolution of the PDFs, and a C++ wrapper that
    provides one with the analytical solutions in the asymptotic $z \to 1$
    region. Moreover, the possibility is given to the user to output the PDFs
    as grids compliant with the
    [LHAPDF](https://lhapdf.hepforge.org/index.html) format, that can be
    employed at a later stage. Regardless of whether the numerical solution is
    computed at runtime or read from the grids, eMELA offers the possibility
    to switch to the analytical solution in the asymptotic region. This must be
    considered as the default option when using the PDFs for physics
    simulations.

    **Note**: eMELA supersedes [ePDF](https://github.com/gstagnit/ePDF), that
    was limited to the evolution with a single lepton in the $\overline{\rm MS}$
    renormalisation and factorisation schemes.
  license: MIT
  license_family: MIT
  license_file: source/LICENSE
  dev_url: https://github.com/gstagnit/eMELA

extra:
  recipe-maintainers:
    - gstagnit
    - matthewfeickert
